# Generated by Django 5.1.6 on 2025-03-03 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('codigo', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Código')),
                ('codigo_empresa', models.BigIntegerField(verbose_name='Código Empresa')),
                ('nome_empresa', models.CharField(max_length=200, verbose_name='Nome Empresa')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('codigo_unidade', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Unidade')),
                ('nome_unidade', models.CharField(blank=True, max_length=130, null=True, verbose_name='Nome Unidade')),
                ('codigo_setor', models.CharField(blank=True, max_length=12, null=True, verbose_name='Código Setor')),
                ('nome_setor', models.CharField(blank=True, max_length=130, null=True, verbose_name='Nome Setor')),
                ('codigo_cargo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Cargo')),
                ('nome_cargo', models.CharField(blank=True, max_length=130, null=True, verbose_name='Nome Cargo')),
                ('cbo_cargo', models.CharField(blank=True, max_length=10, null=True, verbose_name='CBO Cargo')),
                ('ccusto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Centro de Custo')),
                ('nome_centro_custo', models.CharField(blank=True, max_length=130, null=True, verbose_name='Nome Centro Custo')),
                ('matricula_funcionario', models.CharField(blank=True, max_length=30, null=True, verbose_name='Matrícula Funcionário')),
                ('cpf', models.CharField(blank=True, max_length=19, null=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=19, null=True, verbose_name='RG')),
                ('uf_rg', models.CharField(blank=True, max_length=10, null=True, verbose_name='UF RG')),
                ('orgao_emissor_rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='Órgão Emissor RG')),
                ('situacao', models.CharField(blank=True, max_length=12, null=True, verbose_name='Situação')),
                ('sexo', models.IntegerField(blank=True, choices=[(1, 'Masculino'), (2, 'Feminino')], null=True, verbose_name='Sexo')),
                ('pis', models.CharField(blank=True, max_length=20, null=True, verbose_name='PIS')),
                ('ctps', models.CharField(blank=True, max_length=30, null=True, verbose_name='CTPS')),
                ('serie_ctps', models.CharField(blank=True, max_length=25, null=True, verbose_name='Série CTPS')),
                ('estado_civil', models.IntegerField(blank=True, choices=[(1, 'Solteiro(a)'), (2, 'Casado(a)'), (3, 'Separado(a)'), (4, 'Desquitado(a)'), (5, 'Viuvo(a)'), (6, 'Outros'), (7, 'Divorciado(a)')], null=True, verbose_name='Estado Civil')),
                ('tipo_contratacao', models.IntegerField(blank=True, null=True, verbose_name='Tipo Contratação')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('data_admissao', models.DateField(blank=True, null=True, verbose_name='Data de Admissão')),
                ('data_demissao', models.DateField(blank=True, null=True, verbose_name='Data de Demissão')),
                ('endereco', models.CharField(blank=True, max_length=110, null=True, verbose_name='Endereço')),
                ('numero_endereco', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=80, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=20, null=True, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('telefone_residencial', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Residencial')),
                ('telefone_celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Celular')),
                ('email', models.CharField(blank=True, max_length=400, null=True, verbose_name='Email')),
                ('deficiente', models.BooleanField(default=False, verbose_name='Deficiente')),
                ('deficiencia', models.CharField(blank=True, max_length=861, null=True, verbose_name='Deficiência')),
                ('nm_mae_funcionario', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nome da Mãe')),
                ('data_ultima_alteracao', models.DateField(blank=True, null=True, verbose_name='Data Última Alteração')),
                ('matricula_rh', models.CharField(blank=True, max_length=30, null=True, verbose_name='Matrícula RH')),
                ('cor', models.IntegerField(blank=True, null=True, verbose_name='Cor')),
                ('escolaridade', models.IntegerField(blank=True, null=True, verbose_name='Escolaridade')),
                ('naturalidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Naturalidade')),
                ('ramal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ramal')),
                ('regime_revezamento', models.IntegerField(blank=True, null=True, verbose_name='Regime Revezamento')),
                ('regime_trabalho', models.CharField(blank=True, max_length=500, null=True, verbose_name='Regime Trabalho')),
                ('tel_comercial', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Comercial')),
                ('turno_trabalho', models.IntegerField(blank=True, null=True, verbose_name='Turno Trabalho')),
                ('rh_unidade', models.CharField(blank=True, max_length=80, null=True, verbose_name='RH Unidade')),
                ('rh_setor', models.CharField(blank=True, max_length=80, null=True, verbose_name='RH Setor')),
                ('rh_cargo', models.CharField(blank=True, max_length=80, null=True, verbose_name='RH Cargo')),
                ('rh_centro_custo_unidade', models.CharField(blank=True, max_length=80, null=True, verbose_name='RH Centro Custo Unidade')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='dashboard.empresa')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'db_table': 'funcionarios',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['codigo'], name='funcionario_codigo_18e4b3_idx'), models.Index(fields=['nome'], name='funcionario_nome_9aa946_idx'), models.Index(fields=['cpf'], name='funcionario_cpf_afb6a8_idx'), models.Index(fields=['codigo_empresa'], name='funcionario_codigo__767e71_idx'), models.Index(fields=['data_admissao'], name='funcionario_data_ad_476140_idx'), models.Index(fields=['situacao'], name='funcionario_situaca_1e432b_idx')],
            },
        ),
    ]
