# Generated by Django 5.1.6 on 2025-03-06 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absenteismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=130, verbose_name='Unidade')),
                ('setor', models.CharField(max_length=130, verbose_name='Setor')),
                ('matricula_func', models.CharField(max_length=30, verbose_name='Matrícula Funcionário')),
                ('dt_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('sexo', models.IntegerField(blank=True, choices=[(1, 'Masculino'), (2, 'Feminino')], null=True, verbose_name='Sexo')),
                ('tipo_atestado', models.IntegerField(choices=[(1, 'Atestado médico'), (2, 'Licença maternidade'), (3, 'Acidente de trabalho'), (4, 'Outros afastamentos')], default=1, verbose_name='Tipo de Atestado')),
                ('dt_inicio_atestado', models.DateField(verbose_name='Data Início Atestado')),
                ('dt_fim_atestado', models.DateField(verbose_name='Data Fim Atestado')),
                ('hora_inicio_atestado', models.CharField(blank=True, max_length=5, null=True, verbose_name='Hora Início Atestado')),
                ('hora_fim_atestado', models.CharField(blank=True, max_length=5, null=True, verbose_name='Hora Fim Atestado')),
                ('dias_afastados', models.IntegerField(verbose_name='Dias Afastados')),
                ('horas_afastado', models.CharField(blank=True, max_length=5, null=True, verbose_name='Horas Afastado')),
                ('cid_principal', models.CharField(blank=True, max_length=10, null=True, verbose_name='CID Principal')),
                ('descricao_cid', models.CharField(blank=True, max_length=264, null=True, verbose_name='Descrição CID')),
                ('grupo_patologico', models.CharField(blank=True, max_length=80, null=True, verbose_name='Grupo Patológico')),
                ('tipo_licenca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Licença')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absenteismos', to='dashboard.empresa', verbose_name='Empresa')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='absenteismos', to='dashboard.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Absenteísmo',
                'verbose_name_plural': 'Absenteísmos',
                'db_table': 'absenteismo',
                'ordering': ['-dt_inicio_atestado', 'matricula_func'],
                'indexes': [models.Index(fields=['empresa'], name='absenteismo_empresa_910783_idx'), models.Index(fields=['matricula_func'], name='absenteismo_matricu_596bea_idx'), models.Index(fields=['dt_inicio_atestado', 'dt_fim_atestado'], name='absenteismo_dt_inic_d75a47_idx'), models.Index(fields=['tipo_atestado'], name='absenteismo_tipo_at_048285_idx'), models.Index(fields=['cid_principal'], name='absenteismo_cid_pri_d7be98_idx')],
            },
        ),
    ]
