# Generated by Django 5.1.6 on 2025-03-11 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_absenteismo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empresa', models.BigIntegerField(verbose_name='Código Empresa')),
                ('nome_abreviado', models.CharField(max_length=60, verbose_name='Nome Abreviado')),
                ('unidade', models.CharField(max_length=130, verbose_name='Unidade')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('bairro', models.CharField(max_length=80, verbose_name='Bairro')),
                ('endereco', models.CharField(max_length=110, verbose_name='Endereço')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('cnpj_unidade', models.CharField(max_length=20, verbose_name='CNPJ Unidade')),
                ('setor', models.CharField(max_length=130, verbose_name='Setor')),
                ('cargo', models.CharField(max_length=130, verbose_name='Cargo')),
                ('codigo_funcionario', models.BigIntegerField(verbose_name='Código Funcionário')),
                ('cpf_funcionario', models.CharField(max_length=14, verbose_name='CPF Funcionário')),
                ('matricula', models.CharField(max_length=30, verbose_name='Matrícula')),
                ('data_admissao', models.DateField(verbose_name='Data de Admissão')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do Funcionário')),
                ('email_funcionario', models.CharField(blank=True, max_length=400, null=True, verbose_name='Email do Funcionário')),
                ('telefone_funcionario', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Funcionário')),
                ('codigo_exame', models.CharField(max_length=20, verbose_name='Código do Exame')),
                ('exame', models.CharField(max_length=200, verbose_name='Exame')),
                ('ultimo_pedido', models.DateField(blank=True, null=True, verbose_name='Data do Último Pedido')),
                ('data_resultado', models.DateField(blank=True, null=True, verbose_name='Data do Resultado')),
                ('periodicidade', models.IntegerField(verbose_name='Periodicidade (meses)')),
                ('refazer', models.BooleanField(default=False, verbose_name='Necessário Refazer')),
                ('status', models.CharField(default='PENDENTE', max_length=20, verbose_name='Status')),
                ('data_convocacao', models.DateField(auto_now_add=True, verbose_name='Data da Convocação')),
                ('data_agendamento', models.DateField(blank=True, null=True, verbose_name='Data de Agendamento')),
                ('hora_agendamento', models.TimeField(blank=True, null=True, verbose_name='Hora de Agendamento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocacoes', to='dashboard.empresa', verbose_name='Empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocacoes', to='dashboard.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Convocação de Exame',
                'verbose_name_plural': 'Convocações de Exames',
                'db_table': 'convocacoes',
                'ordering': ['-data_convocacao', 'nome'],
                'indexes': [models.Index(fields=['empresa'], name='convocacoes_empresa_825f51_idx'), models.Index(fields=['funcionario'], name='convocacoes_funcion_0943ff_idx'), models.Index(fields=['codigo_funcionario'], name='convocacoes_codigo__45ea1c_idx'), models.Index(fields=['codigo_exame'], name='convocacoes_codigo__f488b8_idx'), models.Index(fields=['data_convocacao'], name='convocacoes_data_co_2eb2ea_idx'), models.Index(fields=['status'], name='convocacoes_status_a67b54_idx')],
            },
        ),
    ]
