# Generated by Django 5.1.6 on 2025-03-11 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_convocacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocacao',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocacoes', to='dashboard.empresa'),
        ),
        migrations.AlterField(
            model_name='convocacao',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocacoes', to='dashboard.funcionario'),
        ),
    ]
