# Generated by Django 5.1.6 on 2025-03-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_convocacao_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocacao',
            name='refazer',
            field=models.DateField(blank=True, null=True, verbose_name='Data para Refazer'),
        ),
    ]
